# Generated by Django 3.2.10 on 2023-12-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterazioniSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_utente', models.IntegerField()),
                ('id_piattaforma', models.IntegerField()),
                ('id_contenuti', models.IntegerField()),
                ('id_data', models.IntegerField()),
                ('commenti', models.IntegerField()),
                ('like', models.IntegerField()),
                ('condivisioni', models.IntegerField()),
                ('click', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
