# Generated by Django 5.0.1 on 2024-01-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SentimentoMessaggi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_tipologia", models.IntegerField()),
                ("id_piattaforma", models.IntegerField()),
                ("id_utente", models.IntegerField()),
                ("id_data", models.IntegerField()),
                ("nuemero_messaggi", models.IntegerField()),
                ("percentuale_sentimento", models.IntegerField()),
                ("sentimento_medio", models.IntegerField()),
                ("timestamp", models.DateTimeField()),
            ],
        ),
    ]
