# Generated by Django 5.0.1 on 2024-01-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Marketing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_campagna", models.IntegerField()),
                ("id_piattaforma", models.IntegerField()),
                ("id_utente", models.IntegerField()),
                ("id_data", models.IntegerField()),
                ("costo", models.IntegerField()),
                ("profitto", models.IntegerField()),
                ("roi", models.IntegerField()),
                ("timestamp", models.DateTimeField()),
            ],
        ),
    ]
